/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A single NDJSON line from the sc-tools test streaming reporter
 */
export type SCToolsStreamingEvent =
  | {
      coverageIndex: SrcLocRanges[];
      event: "suite_started";
      packageRoot?: string;
      tests: TestInfo[];
      [k: string]: unknown;
    }
  | {
      event: "test_started";
      id: number;
      [k: string]: unknown;
    }
  | {
      event: "test_progress";
      id: number;
      message: string;
      percent: number;
      [k: string]: unknown;
    }
  | {
      description: string;
      duration: number;
      event: "test_done";
      failure?: FailureInfo;
      id: number;
      monitoring_stats?: MonitoringStats;
      success: boolean;
      threat_model?: ThreatModelSummary;
      [k: string]: unknown;
    }
  | {
      category: string;
      covered: SrcLocRanges[];
      event: "test_trace";
      id: number;
      trace: IterationTrace;
      [k: string]: unknown;
    }
  | {
      duration: number;
      event: "suite_done";
      failed: number;
      passed: number;
      [k: string]: unknown;
    };
export type IterationStatus =
  | {
      status: "success";
      [k: string]: unknown;
    }
  | {
      message: string;
      status: "failure";
      [k: string]: unknown;
    }
  | {
      message: string;
      status: "discarded";
      [k: string]: unknown;
    };
export type TxMod =
  | {
      type: "removeInput";
      utxo: string;
      [k: string]: unknown;
    }
  | {
      index: number;
      type: "removeOutput";
      [k: string]: unknown;
    }
  | {
      address: string | null;
      datum: string | null;
      index: number;
      referenceScript: string | null;
      type: "changeOutput";
      value: ValueSummary | null;
      [k: string]: unknown;
    }
  | {
      address: string | null;
      datum: string | null;
      referenceScript: string | null;
      type: "changeInput";
      utxo: string;
      value: ValueSummary | null;
      [k: string]: unknown;
    }
  | {
      datum: string | null;
      redeemer: string | null;
      referenceScript: string | null;
      type: "changeScriptInput";
      utxo: string;
      value: ValueSummary | null;
      [k: string]: unknown;
    }
  | {
      lowerBound: string | null;
      type: "changeValidityRange";
      upperBound: string | null;
      [k: string]: unknown;
    }
  | {
      address: string;
      datum: string | null;
      referenceScript: string;
      type: "addOutput";
      value: ValueSummary;
      [k: string]: unknown;
    }
  | {
      address: string;
      datum: string | null;
      isReferenceInput: boolean;
      referenceScript: string;
      type: "addInput";
      value: ValueSummary;
      [k: string]: unknown;
    }
  | {
      datum: string | null;
      redeemer: string;
      scriptHash: string;
      type: "addReferenceScriptInput";
      value: ValueSummary;
      [k: string]: unknown;
    }
  | {
      datum: string | null;
      redeemer: string;
      referenceScript: string;
      type: "addPlutusScriptInput";
      value: ValueSummary;
      [k: string]: unknown;
    }
  | {
      datum: string | null;
      referenceScript: string;
      type: "addPlutusScriptReferenceInput";
      value: ValueSummary;
      [k: string]: unknown;
    }
  | {
      isReferenceInput: boolean;
      referenceScript: string;
      type: "addSimpleScriptInput";
      value: ValueSummary;
      [k: string]: unknown;
    }
  | {
      assetName: string;
      quantity: number;
      redeemer: string;
      type: "addPlutusScriptMint";
      [k: string]: unknown;
    }
  | {
      keyHash: string;
      type: "removeRequiredSigner";
      [k: string]: unknown;
    }
  | {
      type: "replaceTx";
      [k: string]: unknown;
    };
export type ThreatModelTraceOutcome =
  | {
      status: "passed";
      [k: string]: unknown;
    }
  | {
      reason: string;
      status: "failed";
      [k: string]: unknown;
    }
  | {
      reason: string;
      status: "skipped";
      [k: string]: unknown;
    }
  | {
      message: string;
      status: "error";
      [k: string]: unknown;
    };
export type TransitionResult =
  | {
      status: "success";
      txId: string;
      [k: string]: unknown;
    }
  | {
      error: string;
      status: "failure";
      [k: string]: unknown;
    };

export interface SrcLocRanges {
  endCols: number[];
  endLines: number[];
  file: string;
  startCols: number[];
  startLines: number[];
  [k: string]: unknown;
}
export interface TestInfo {
  id: number;
  name: string;
  path: string[];
  srcLoc?: {
    endCol: number;
    endLine: number;
    file: string;
    startCol: number;
    startLine: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface FailureInfo {
  message: string;
  reason: string;
  [k: string]: unknown;
}
export interface MonitoringStats {
  classes: MonitoringClassStat[];
  labels: MonitoringLabelStat[];
  numDiscarded: number;
  numTests: number;
  tables: MonitoringTableStat[];
  [k: string]: unknown;
}
export interface MonitoringClassStat {
  count: number;
  name: string;
  percent: number;
  [k: string]: unknown;
}
export interface MonitoringLabelStat {
  count: number;
  labels: string[];
  percent: number;
  [k: string]: unknown;
}
export interface MonitoringTableStat {
  entries: MonitoringTableEntry[];
  name: string;
  [k: string]: unknown;
}
export interface MonitoringTableEntry {
  count: number;
  value: string;
  [k: string]: unknown;
}
export interface ThreatModelSummary {
  errors: number;
  failed: number;
  name: string;
  passed: number;
  skipped: number;
  tested: number;
  total: number;
  [k: string]: unknown;
}
export interface IterationTrace {
  index: number;
  status: IterationStatus;
  threatModels: ThreatModelTrace[];
  transitions: Transition[];
  [k: string]: unknown;
}
export interface ThreatModelTrace {
  covered: SrcLocRanges[];
  modifications: TxMod[];
  modifiedTx: TxSummary | null;
  name: string;
  originalTx: TxSummary;
  outcome: ThreatModelTraceOutcome;
  targetTxIndex: number;
  testId: number;
  [k: string]: unknown;
}
export interface ValueSummary {
  assets: AssetSummary[];
  lovelace: number;
  [k: string]: unknown;
}
export interface AssetSummary {
  name: string;
  policyId: string;
  quantity: number;
  [k: string]: unknown;
}
export interface TxSummary {
  fee: number;
  id: string | null;
  inputs: TxInputSummary[];
  mint: ValueSummary | null;
  outputs: TxOutputSummary[];
  signers: (string | null)[];
  validRange: string | null;
  [k: string]: unknown;
}
/**
 * Tier 1 (redeemerRaw, redeemerConstr) is always present for script inputs; Tier 2 (redeemerKind, redeemerPayload) is only populated when the TestingInterface instance overrides redeemerTagger. All four redeemer fields are nullable (null for non-script inputs, or when Tier 2 is not opted in).
 */
export interface TxInputSummary {
  address: string;
  redeemerConstr: number | null;
  redeemerKind: string | null;
  redeemerPayload: unknown;
  redeemerRaw: string | null;
  utxo: string;
  value: ValueSummary;
  [k: string]: unknown;
}
export interface TxOutputSummary {
  address: string;
  datum: string | null;
  utxo: string;
  value: ValueSummary;
  [k: string]: unknown;
}
export interface Transition {
  action: string;
  result: TransitionResult;
  stateAfter: unknown;
  stateBefore: unknown;
  stepIndex: number;
  transaction: TxSummary | null;
  [k: string]: unknown;
}
